improvements for performance
DistributedCollective/governance-dapp pull request #136
Opened 2021-12-08 08:27 UTC by creed-victor

- use rpc nodes instead of ws where possible
- moved proposal details from modal to dedicated page (prevents downloading data from other proposals)
- fixes progress bar image (it respects % now)

2021-12-08 10:10 UTC, tiltom requested changes

2021-12-08 10:10 UTC, tiltom commented on src/app/containers/BlockChainProvider/saga.ts
> +    return () => {};
Create `noop` constant (as we have in our frontend repo) and use it here.

2021-12-08 10:10 UTC, tiltom commented on src/app/containers/ProposalRow/index.tsx
>  interface Props {
```suggestion
interface IProposalRowProps {
```

2021-12-08 10:10 UTC, tiltom commented on src/app/containers/ProposalRow/index.tsx
> +                  <em>Loading, please wait..</em>
```suggestion
                  <em>Loading, please wait...</em>
```

2021-12-08 10:10 UTC, tiltom commented on src/app/containers/ProposalRow/index.tsx
>                <Linkify newTab={true}>
We have a duplicate on line `84`, pls extract it to a component (you can leave the new component in this file).

2021-12-10 14:22 UTC, Alitasovryn commented
<img width="1357" alt="Screen Shot 2021-12-10 at 9 18 53 AM" src="https://user-images.githubusercontent.com/94629682/145588596-37d787af-1661-4f1d-bb87-ff0dd6078ae0.png">

2021-12-10 14:22 UTC, Alitasovryn commented
Works fine

2021-12-10 14:22 UTC, Alitasovryn approved these changes

2021-12-11 18:13 UTC, soulBit approved these changes
Changes look good, proposals load almost 2x faster now 😄 

I made two small updates - renamed Quarums -> QuorumDetails, and styling for new details to match the rest of the page content

2021-12-13 09:35 UTC, tiltom approved these changes

2021-12-13 14:11 UTC, JoeStorm99 approved these changes

2022-01-11 13:55 UTC, merged